"""initial production schema

Revision ID: 316f91001198
Revises:
Create Date: 2026-08-10 06:11:29.548669
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '316f91001198'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('time_zone', sa.String(length=80), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_accounts_external_id'), 'ads_accounts', ['external_id'], unique=True)
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=True),
    sa.Column('verified_name', sa.String(length=255), nullable=False),
    sa.Column('verified_location', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.Enum('BRAND_OWNER', 'AGENCY', 'AFFILIATE_OR_PUBLISHER', 'RESELLER', 'UNKNOWN', name='advertiserclassification', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    op.create_index(op.f('ix_advertisers_verified_name'), 'advertisers', ['verified_name'], unique=False)
    op.create_table('affiliate_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('platform_type', sa.String(length=80), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('supports_api', sa.Boolean(), nullable=False),
    sa.Column('supports_subid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_networks_name'), 'affiliate_networks', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'IMPORT', 'SYNC', 'APPROVE', 'BLOCK', name='auditaction', native_enum=False), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_domain', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_index(op.f('ix_merchants_website_domain'), 'merchants', ['website_domain'], unique=True)
    op.create_table('raw_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('visible_text', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('RAW', 'PARSED', 'NEEDS_REVIEW', 'REJECTED', name='capturestatus', native_enum=False), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('parsed_payload', sa.JSON(), nullable=False),
    sa.Column('capture_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_hash')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'STALE', 'AUTH_FAILED', 'RATE_LIMITED', 'ERROR', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_connector'), 'sync_runs', ['connector'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['affiliate_networks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_payouts_paid_at'), 'payouts', ['paid_at'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('signup_url', sa.String(length=1000), nullable=True),
    sa.Column('dashboard_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'APPLYING', 'PENDING_APPROVAL', 'ACTIVE', 'PAUSED', 'REJECTED', 'CLOSED', name='programstatus', native_enum=False), nullable=False),
    sa.Column('paid_search_permission', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('brand_keyword_permission', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('non_brand_permission', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('direct_link_permission', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('trademark_in_ad_copy_permission', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('required_negative_keywords', sa.JSON(), nullable=False),
    sa.Column('allowed_geos', sa.JSON(), nullable=False),
    sa.Column('blocked_geos', sa.JSON(), nullable=False),
    sa.Column('last_terms_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_id'], ['affiliate_networks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'name', name='uq_program_merchant_name')
    )
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission_type', sa.Enum('ONE_TIME', 'RECURRING_LIMITED', 'RECURRING_LIFETIME', 'HYBRID', name='commissiontype', native_enum=False), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('commission_flat', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('recurring_months', sa.Integer(), nullable=True),
    sa.Column('cookie_days', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('refund_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'external_id', name='uq_offer_program_external')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('affiliate_program_found', sa.Boolean(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('watch_status', sa.Enum('NEW', 'WATCH', 'HIGH_VALUE', 'QUALIFY', 'IGNORE', name='watchstatus', native_enum=False), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_brand_name'), 'projects', ['brand_name'], unique=False)
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=True)
    op.create_table('terms_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('PROHIBITED', 'NON_BRAND_ONLY', 'BRAND_ALLOWED', 'APPROVAL_REQUIRED', 'AMBIGUOUS', 'NOT_CHECKED', name='permissionstatus', native_enum=False), nullable=False),
    sa.Column('applies_to', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_hash')
    )
    op.create_index('ix_terms_program_checked', 'terms_evidence', ['program_id', 'checked_at'], unique=False)
    op.create_table('ad_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('raw_capture_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('ad_format', sa.String(length=80), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_url', sa.String(length=1000), nullable=True),
    sa.Column('landing_domain', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_capture_id'], ['raw_captures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertiser_id', 'project_id', 'content_hash', 'snapshot_date', name='uq_observation_snapshot')
    )
    op.create_index(op.f('ix_ad_observations_advertiser_id'), 'ad_observations', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_observations_country'), 'ad_observations', ['country'], unique=False)
    op.create_index(op.f('ix_ad_observations_landing_domain'), 'ad_observations', ['landing_domain'], unique=False)
    op.create_index(op.f('ix_ad_observations_project_id'), 'ad_observations', ['project_id'], unique=False)
    op.create_index(op.f('ix_ad_observations_snapshot_date'), 'ad_observations', ['snapshot_date'], unique=False)
    op.create_index('ix_observation_project_date', 'ad_observations', ['project_id', 'snapshot_date'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_account_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('channel_type', sa.String(length=80), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('launch_gate_status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ads_account_id'], ['ads_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ads_account_id', 'external_id', name='uq_campaign_account_external')
    )
    op.create_index(op.f('ix_campaigns_ads_account_id'), 'campaigns', ['ads_account_id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('gbraid', sa.String(length=255), nullable=True),
    sa.Column('wbraid', sa.String(length=255), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('ad_group_external_id', sa.String(length=64), nullable=True),
    sa.Column('criterion_id', sa.String(length=64), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=True),
    sa.Column('match_type', sa.String(length=40), nullable=True),
    sa.Column('device', sa.String(length=40), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affiliate_subid', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('quality', sa.Enum('OBSERVED', 'MATCHED', 'MODELED', 'UNKNOWN', name='dataquality', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_affiliate_subid'), 'clicks', ['affiliate_subid'], unique=True)
    op.create_index(op.f('ix_clicks_clicked_at'), 'clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_clicks_gbraid'), 'clicks', ['gbraid'], unique=False)
    op.create_index(op.f('ix_clicks_gclid'), 'clicks', ['gclid'], unique=True)
    op.create_index(op.f('ix_clicks_wbraid'), 'clicks', ['wbraid'], unique=False)
    op.create_table('spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('normalized_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('normalized_currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('quality', sa.Enum('OBSERVED', 'MATCHED', 'MODELED', 'UNKNOWN', name='dataquality', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'spend_date', 'source', name='uq_spend_campaign_date')
    )
    op.create_index(op.f('ix_spend_spend_date'), 'spend', ['spend_date'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('click_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.Enum('OBSERVED', 'MATCHED', 'MODELED', 'UNKNOWN', name='dataquality', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_hash')
    )
    op.create_index(op.f('ix_conversions_external_id'), 'conversions', ['external_id'], unique=True)
    op.create_index(op.f('ix_conversions_occurred_at'), 'conversions', ['occurred_at'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('conversion_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('normalized_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('normalized_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_source', sa.String(length=120), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'LOCKED', 'PAID', 'REJECTED', 'REFUNDED', 'CHARGEBACK', name='commissionstate', native_enum=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('quality', sa.Enum('OBSERVED', 'MATCHED', 'MODELED', 'UNKNOWN', name='dataquality', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_external_id'), 'commissions', ['external_id'], unique=True)
    op.create_index(op.f('ix_commissions_occurred_at'), 'commissions', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissions_occurred_at'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_external_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_conversions_occurred_at'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_external_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_spend_spend_date'), table_name='spend')
    op.drop_table('spend')
    op.drop_index(op.f('ix_clicks_wbraid'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_gclid'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_gbraid'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_clicked_at'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_affiliate_subid'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_ads_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_observation_project_date', table_name='ad_observations')
    op.drop_index(op.f('ix_ad_observations_snapshot_date'), table_name='ad_observations')
    op.drop_index(op.f('ix_ad_observations_project_id'), table_name='ad_observations')
    op.drop_index(op.f('ix_ad_observations_landing_domain'), table_name='ad_observations')
    op.drop_index(op.f('ix_ad_observations_country'), table_name='ad_observations')
    op.drop_index(op.f('ix_ad_observations_advertiser_id'), table_name='ad_observations')
    op.drop_table('ad_observations')
    op.drop_index('ix_terms_program_checked', table_name='terms_evidence')
    op.drop_table('terms_evidence')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_index(op.f('ix_projects_brand_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('offers')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_payouts_paid_at'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_sync_runs_connector'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('raw_captures')
    op.drop_index(op.f('ix_merchants_website_domain'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_affiliate_networks_name'), table_name='affiliate_networks')
    op.drop_table('affiliate_networks')
    op.drop_index(op.f('ix_advertisers_verified_name'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_ads_accounts_external_id'), table_name='ads_accounts')
    op.drop_table('ads_accounts')
    # ### end Alembic commands ###
