from enum import StrEnum


class PermissionStatus(StrEnum):
    PROHIBITED = "PROHIBITED"
    NON_BRAND_ONLY = "NON_BRAND_ONLY"
    BRAND_ALLOWED = "BRAND_ALLOWED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    AMBIGUOUS = "AMBIGUOUS"
    CONFLICT = "CONFLICT"
    NOT_CHECKED = "NOT_CHECKED"


class EvidenceReviewStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class SourceAuthority(StrEnum):
    OFFICIAL = "OFFICIAL"
    PARTNER_PORTAL = "PARTNER_PORTAL"
    WRITTEN_CONFIRMATION = "WRITTEN_CONFIRMATION"
    THIRD_PARTY = "THIRD_PARTY"
    UNKNOWN = "UNKNOWN"


class ResearchStatus(StrEnum):
    PROPOSAL_READY = "PROPOSAL_READY"
    CONFLICT = "CONFLICT"
    RETRY_REQUIRED = "RETRY_REQUIRED"
    MANUAL_INPUT_REQUIRED = "MANUAL_INPUT_REQUIRED"


class TermsWarningStatus(StrEnum):
    TERMS_OK = "TERMS_OK"
    WARNING_TERMS_UNVERIFIED = "WARNING_TERMS_UNVERIFIED"
    WARNING_TERMS_CONFLICT = "WARNING_TERMS_CONFLICT"
    WARNING_TERMS_PROHIBITED = "WARNING_TERMS_PROHIBITED"
    WARNING_APPROVAL_REQUIRED = "WARNING_APPROVAL_REQUIRED"


class CommissionType(StrEnum):
    ONE_TIME = "ONE_TIME"
    RECURRING_UNSPECIFIED = "RECURRING_UNSPECIFIED"
    RECURRING_LIMITED = "RECURRING_LIMITED"
    RECURRING_LIFETIME = "RECURRING_LIFETIME"
    HYBRID = "HYBRID"


class CommissionState(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"
    PAID = "PAID"
    REJECTED = "REJECTED"
    REFUNDED = "REFUNDED"
    CHARGEBACK = "CHARGEBACK"


class DataQuality(StrEnum):
    OBSERVED = "OBSERVED"
    IMPORTED = "IMPORTED"
    MATCHED = "MATCHED"
    ESTIMATED = "ESTIMATED"
    MODELED = "MODELED"
    UNKNOWN = "UNKNOWN"


class FxRateReviewStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ReconciliationStatus(StrEnum):
    ATTRIBUTED = "ATTRIBUTED"
    PARTIAL = "PARTIAL"
    UNATTRIBUTED = "UNATTRIBUTED"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"


class SyncStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    AUTH_FAILED = "AUTH_FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    ERROR = "ERROR"


class ProgramStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    APPLYING = "APPLYING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class AdvertiserClassification(StrEnum):
    BRAND_OWNER = "BRAND_OWNER"
    AGENCY = "AGENCY"
    AFFILIATE_OR_PUBLISHER = "AFFILIATE_OR_PUBLISHER"
    RESELLER = "RESELLER"
    UNKNOWN = "UNKNOWN"


class WatchStatus(StrEnum):
    NEW = "NEW"
    WATCH = "WATCH"
    HIGH_VALUE = "HIGH_VALUE"
    QUALIFY = "QUALIFY"
    IGNORE = "IGNORE"


class ProjectStage(StrEnum):
    INTAKE = "INTAKE"
    RESEARCH = "RESEARCH"
    EVALUATION = "EVALUATION"
    PREP = "PREP"
    LIVE = "LIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


class CampPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    DEPLOYED = "DEPLOYED"


class RegistrationStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    APPLYING = "APPLYING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    BLOCKED_REGISTRATION = "BLOCKED_REGISTRATION"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class AutomationJobType(StrEnum):
    TERMS_RESEARCH = "TERMS_RESEARCH"
    ADS_IMPORT = "ADS_IMPORT"
    COMMISSION_IMPORT = "COMMISSION_IMPORT"
    CAMPAIGN_AUTO_MAP = "CAMPAIGN_AUTO_MAP"
    PROJECT_DISCOVERY = "PROJECT_DISCOVERY"
    ADVERTISER_REFRESH = "ADVERTISER_REFRESH"


class AutomationJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    DEAD_LETTER = "DEAD_LETTER"
    CANCELLED = "CANCELLED"


class CaptureStatus(StrEnum):
    RAW = "RAW"
    PARSED = "PARSED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    IMPORT = "IMPORT"
    SYNC = "SYNC"
    APPROVE = "APPROVE"
    BLOCK = "BLOCK"
